export const TOPICS = [
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    emoji: '\u26bd',
    subtopics: [
      { id: 'running', name: 'Running & Marathons', emoji: '\ud83c\udfc3', desc: 'Training routines, best routes, and gear.', questions: ['Does the increasing reliance on carbon-plated shoes and advanced metrics diminish the raw, human purity of distance running?', 'Is the legendary "runner\'s high" a genuine biological reward, or merely a psychological coping mechanism for sustained physical trauma?', 'If you could perfectly train for a marathon without ever experiencing the physical pain of the process, would crossing the finish line still hold the same emotional weight?'] },
      { id: 'team-sports', name: 'Team Sports', emoji: '\ud83c\udfc8', desc: 'Football, Basketball, Ice Hockey, and Rugby.', questions: ['When a team achieves a flawless, dynastic run, is it more a triumph of a single visionary coach\'s system or the spontaneous chemistry of the players?', 'Does the extreme optimization of sports through data analytics risk solving the "game" and stripping away the unpredictable magic of human error?', 'At what point does fan loyalty cross the line from healthy community bonding to tribal, toxic identification?'] },
      { id: 'martial-arts', name: 'Martial Arts & Combat', emoji: '\ud83e\udd4a', desc: 'Boxing, BJJ, MMA, and traditional disciplines.', questions: ['Is the ultimate mastery of a martial art achieved when a practitioner reaches a state of mind where they never actually have to use it?', 'How does the modernization and gamification of mixed martial arts impact the ancient, spiritual philosophies that originally birthed these combat styles?', 'What is the psychological difference between the aggression required to survive a street altercation and the controlled violence of a sanctioned ring?'] },
      { id: 'mind-body', name: 'Mind & Body', emoji: '\ud83e\uddd8', desc: 'Yoga, Pilates, and meditation practices.', questions: ['Where exactly is the neurological line between pushing your physical limits for necessary growth and dangerously ignoring your body\'s survival instincts?', 'Can purely physical exhaustion actually cure psychological stress, or does it just temporarily mask it?', 'How much of "hitting the wall" in endurance fitness is a physical failure of muscles, versus a deliberate safety shut-off by the brain?'] },
      { id: 'extreme-outdoor', name: 'Extreme & Outdoor', emoji: '\ud83e\uddd7', desc: 'Rock climbing, surfing, snowboarding, and mountain biking.', questions: ['What separates a genuine thrill-seeker pushing the boundaries of human capability from someone who simply harbors a reckless death wish?', 'Has the commercialization of extreme feats, like guided tours to the summit of Everest, completely ruined the sacred nature of exploration?', 'If the element of mortal danger was completely removed from extreme sports via safety technology, would the athletes still want to participate?'] },
    ],
  },
  {
    id: 'travel-adventure',
    name: 'Travel & Adventure',
    emoji: '\u2708\ufe0f',
    subtopics: [
      { id: 'backpacking', name: 'Backpacking & Budget Travel', emoji: '\ud83c\udf92', desc: 'Hostels, hitchhiking, and cheap destinations.', questions: ['What is the single most valuable truth you\'ve learned about your own character from being completely, hopelessly lost in a foreign place with no money?', 'Does the modern "digital nomad" lifestyle actually foster global connection, or does it just create isolated bubbles of privilege in developing nations?', 'Is budget backpacking inherently more "authentic," or is that just a romanticized narrative to justify traveling with less comfort?'] },
      { id: 'luxury-resorts', name: 'Luxury & Resorts', emoji: '\ud83c\udfe8', desc: 'Fine hotels, cruises, and all-inclusive getaways.', questions: ['If a luxury resort perfectly isolates you from the harsh realities of the local culture, can it still genuinely be considered "travel," or is it just an expensive simulation?', 'What is the psychological appeal of paying exorbitant amounts of money to have staff anticipate your needs before you even realize them yourself?', 'Does the pursuit of high-end, curated travel experiences strip away the serendipity that makes a journey truly memorable?'] },
      { id: 'cultural-immersion', name: 'Cultural Immersion', emoji: '\ud83c\udf0d', desc: 'Volunteering abroad, living like a local, and language barriers.', questions: ['At what specific point does trying to enthusiastically blend in with a local culture cross the line into performative behavior or cultural appropriation?', 'Can you ever truly understand a culture if you do not speak a single word of its native language, or are universal human gestures enough?', 'Is the desire to find "untouched" or "un-touristy" locations a form of modern colonialism?'] },
      { id: 'road-trips', name: 'Road Trips', emoji: '\ud83d\ude97', desc: 'Van life, scenic routes, and camping.', questions: ['What is the intangible psychological element that transforms a painfully long, monotonous drive into a legendary, bonding road trip?', 'Why do the liminal spaces of road trips—gas stations at 3 AM, empty diners, endless highways—evoke such a specific, melancholic comfort?', 'If teleportation existed, would we eventually deeply miss the physical transition time that a long journey provides?'] },
      { id: 'culinary-tourism', name: 'Culinary Tourism', emoji: '\ud83c\udf5c', desc: 'Traveling for food, wine tasting, and street food tours.', questions: ['Would you rather travel thousands of miles to eat the absolute best version of a dish you already love, or a local delicacy that genuinely terrifies you?', 'Does gentrifying authentic, cheap street food into highly expensive, sit-down restaurant dishes ruin its essence or elevate its culture?', 'How heavily is our perception of a meal\'s "authenticity" influenced by the aesthetic grittiness of the environment we eat it in?'] },
    ],
  },
  {
    id: 'literature',
    name: 'Literature & Reading',
    emoji: '\ud83d\udcda',
    subtopics: [
      { id: 'scifi-fantasy', name: 'Science Fiction & Fantasy', emoji: '\ud83d\udc7d', desc: 'World-building, futuristic concepts, and magic systems.', questions: ['If you were forced to permanently relocate to one fictional universe as an average citizen (not the hero), which would offer the highest actual quality of life?', 'Do "hard" magic systems with strict rules stifle the wonder of fantasy, or do they actually make the world feel more grounded and believable?', 'Is the primary function of modern science fiction to predict the future, or to act as a warning system for the present?'] },
      { id: 'biographies', name: 'Biographies & Memoirs', emoji: '\ud83d\udc64', desc: 'Lessons from historical figures and celebrities.', questions: ['Do you think it is psychologically possible for an autobiography to ever be truly objective, or is human memory inherently fictionalized?', 'How should we grapple with a brilliantly written memoir if we later discover the author fabricated major emotional moments?', 'Is it ethical to write a deeply personal memoir that exposes the secrets and flaws of living family members who didn\'t consent to be characters?'] },
      { id: 'thrillers-crime', name: 'Thrillers & True Crime', emoji: '\ud83d\udd75\ufe0f', desc: 'Unsolved mysteries, psychological thrillers, and detective novels.', questions: ['Why is the human psyche so deeply drawn to—and comforted by—reading about the darkest, most horrific acts people can commit?', 'Does the explosion of true crime media inherently exploit the real-life victims for the sake of our entertainment?', 'What makes the "locked-room mystery" so satisfying to the human brain compared to a sprawling, action-packed conspiracy?'] },
      { id: 'self-help', name: 'Self-Help & Philosophy', emoji: '\ud83d\udca1', desc: 'Personal growth, stoicism, and habit building.', questions: ['If a self-help book actually worked perfectly and completely rewired your mindset, shouldn\'t it inherently be the last one you ever need to buy?', 'Is the modern self-help industry built on empowering people, or on keeping them constantly feeling inadequate so they buy more books?', 'How has the repackaging of ancient philosophies like Stoicism into "hustle culture" mantras changed their original meaning?'] },
      { id: 'comics-manga', name: 'Comics & Manga', emoji: '\ud83e\uddb8', desc: 'Graphic novels, webtoons, and classic comic books.', questions: ['How does the physical pacing of reading panels and turning pages in a comic change the way your brain processes a narrative compared to a text-only novel?', 'Are comic book superheroes simply the modern continuation of ancient Greek and Roman mythologies?', 'Does the restriction of working in black-and-white (as in most manga) force artists to convey emotion more powerfully than in full color?'] },
    ],
  },
  {
    id: 'technology',
    name: 'Technology & The Future',
    emoji: '\ud83d\udcbb',
    subtopics: [
      { id: 'ai', name: 'Artificial Intelligence', emoji: '\ud83e\udd16', desc: 'ChatGPT, automation, and the ethics of AI.', questions: ['If an AI generates a profound masterpiece of literature that moves you to tears, does it matter that there was no human soul behind the words?', 'Should we be more terrified of AI gaining independent, malicious consciousness, or of AI perfectly executing the flawed, biased goals humans give it?', 'If AI can eventually automate all creative and analytical labor, what will become the primary source of human meaning and identity?'] },
      { id: 'space', name: 'Space Exploration', emoji: '\ud83d\ude80', desc: 'Mars missions, the James Webb telescope, and commercial spaceflight.', questions: ['Is it ethically justifiable to spend trillions of dollars colonizing a barren rock like Mars when Earth still has so many preventable humanitarian crises?', 'If we discover definitive proof of microbial life on another planet, how would that actually change the day-to-day philosophy of the average person?', 'What is the greater psychological horror: finding out we are completely alone in the universe, or finding out we are not?'] },
      { id: 'gadgets', name: 'Consumer Gadgets', emoji: '\ud83d\udcf1', desc: 'Smartphones, smart home setups, and wearables.', questions: ['What is one piece of entirely obsolete technology that offered a fundamentally better, more human experience than its modern, highly efficient replacement?', 'Have smartphones actually expanded our connection to the world, or have they just compressed our entire reality into a six-inch glowing rectangle?', 'At what point does the "smart home" stop being a convenience and start being an invasive surveillance apparatus we installed ourselves?'] },
      { id: 'gaming', name: 'Gaming', emoji: '\ud83c\udfae', desc: 'PC building, console wars, indie games, and esports.', questions: ['At what level of graphical fidelity, physical immersion, and narrative depth does a video game stop being a "game" and become an alternate reality?', 'Does the illusion of choice in branching-narrative games actually teach us anything about our real-world morality, or are we just trying to "win"?', 'Why do so many gamers intentionally seek out titles with punishing, frustrating difficulty (like "Soulslikes") in their leisure time?'] },
      { id: 'vr-ar', name: 'Virtual & Augmented Reality', emoji: '\ud83e\udd7d', desc: 'The metaverse, VR gaming, and practical applications.', questions: ['If VR eventually becomes entirely indistinguishable from reality, and offers a perfect life, what will be the human incentive to maintain the flawed physical world?', 'Will the widespread adoption of Augmented Reality completely destroy the concept of a shared, objective public space?', 'How will VR alter our understanding of human empathy if we can literally view the world from behind the eyes of another person?'] },
    ],
  },
  {
    id: 'food-drink',
    name: 'Food & Drink',
    emoji: '\ud83c\udf54',
    subtopics: [
      { id: 'home-cooking', name: 'Home Cooking & Baking', emoji: '\ud83c\udf73', desc: 'Sourdough, meal prep, and family recipes.', questions: ['What deeply ingrained family recipe holds the most emotional weight for you, and what happens to your family\'s history if no one learns to make it?', 'Does relying heavily on food science, thermometers, and exact gram measurements kill the intuitive "soul" of home cooking?', 'Why has baking bread—one of the oldest and most laborious human tasks—become a modern symbol of domestic peace and mindfulness?'] },
      { id: 'street-food', name: 'Street Food Culture', emoji: '\ud83c\udf2e', desc: 'Night markets, food trucks, and regional delicacies.', questions: ['Is the global popularity of street food driven by its actual culinary superiority, or by an exoticized romanticism of working-class culture?', 'How does strict health and safety regulation impact the flavor, history, and authenticity of generational street food vendors?', 'What makes eating a messy, incredibly cheap meal on a plastic stool sometimes more satisfying than a heavily curated fine dining experience?'] },
      { id: 'fine-dining', name: 'Fine Dining', emoji: '\ud83c\udf77', desc: 'Michelin-star restaurants and tasting menus.', questions: ['When you pay hundreds of dollars for a Michelin-star meal, what percentage are you actually paying for the taste versus the sheer theatricality of the experience?', 'Is the pursuit of hyper-innovative fine dining (like molecular gastronomy) a genuine art form, or just an exercise in culinary pretension?', 'Can a restaurant truly be considered "sustainable" if it charges exorbitant prices to serve hyper-local ingredients to the ultra-wealthy?'] },
      { id: 'dietary', name: 'Dietary Lifestyles', emoji: '\ud83e\udd57', desc: 'Veganism, keto, gluten-free, and sustainable eating.', questions: ['How much of our modern, hyper-specific dietary choices (Vegan, Keto, Paleo) are driven by actual health needs versus the psychological desire for a tribal identity?', 'Is ethical consumption even possible in the modern global food supply chain, or are dietary labels just a way to soothe our conscience?', 'Does viewing food purely as "fuel" or "macros" permanently damage our cultural and emotional relationship with eating?'] },
      { id: 'craft-beverages', name: 'Craft Beverages', emoji: '\u2615', desc: 'Specialty coffee, craft breweries, mixology, and wine.', questions: ['Is the modern "craft" beverage movement (beer, coffee, spirits) truly about pursuing a superior taste profile, or is it mostly about the aesthetic of exclusivity?', 'How much does the storytelling and branding behind a bottle of wine or whiskey genuinely alter the way our palate perceives the taste?', 'Have we reached a point where the extreme complexity of craft beverages has alienated the everyday consumer just looking for a drink?'] },
    ],
  },
  {
    id: 'work-career',
    name: 'Work & Career',
    emoji: '\ud83d\udcbc',
    subtopics: [
      { id: 'remote-work', name: 'Remote Work & Digital Nomadism', emoji: '\ud83d\udcbb', desc: 'Home office setups, productivity, and working from abroad.', questions: ['Has the permanent shift to remote work liberated us from corporate oversight, or has it just allowed the office to quietly invade the sanctuary of our homes?', 'What happens to societal cohesion when the "watercooler"—the primary place adults were forced to interact with diverse viewpoints—disappears?', 'Does the digital nomad lifestyle ultimately lead to profound loneliness, stripped of the roots and long-term community that humans evolved to need?'] },
      { id: 'entrepreneurship', name: 'Entrepreneurship', emoji: '\ud83d\ude80', desc: 'Startups, side hustles, and venture capital.', questions: ['Is the concept of the "self-made" entrepreneur an utter myth in a society built entirely on collective infrastructure, luck, and systemic advantages?', 'At what stage of scaling a passionate, ethics-driven startup does it inevitably become the exact type of soulless corporation the founder hated?', 'How has the romanticization of "hustle culture" fundamentally damaged our definition of what constitutes a successful life?'] },
      { id: 'office-dynamics', name: 'Office Dynamics', emoji: '\ud83c\udfe2', desc: 'Navigating corporate culture and workplace friendships.', questions: ['What is the most unspoken, yet universally understood and strictly followed, rule of modern office politics?', 'Does the modern open-plan office foster collaboration, or is it a panopticon designed to ensure constant performative productivity?', 'Why do corporate buzzwords and "management speak" persist when universally everyone claims to hate using them?'] },
      { id: 'career-transitions', name: 'Career Transitions', emoji: '\ud83d\udd04', desc: 'Going back to school, changing industries, and interviewing.', questions: ['When completely reinventing your career from scratch in adulthood, what is the hardest part of your old professional identity to mentally let go of?', 'Is the concept of finding your "dream job" a toxic narrative that sets people up for a lifetime of dissatisfaction with normal, honest labor?', 'How do you navigate the sunk-cost fallacy of leaving a miserable career that you spent a decade and thousands of dollars getting the degree for?'] },
      { id: 'work-life-balance', name: 'Work-Life Balance', emoji: '\u2696\ufe0f', desc: 'Burnout prevention, four-day work weeks, and setting boundaries.', questions: ['Is "work-life balance" a moving target we can never actually hit, and should we be aiming for "work-life integration" instead?', 'If a universal four-day work week was implemented, would we actually rest on that third day, or just fill it with more optimized "side hustles"?', 'At what point did answering an email at 9:00 PM transition from an occasional emergency to an unspoken expectation?'] },
    ],
  },
  {
    id: 'arts-entertainment',
    name: 'Arts & Entertainment',
    emoji: '\ud83c\udfa8',
    subtopics: [
      { id: 'cinema-tv', name: 'Cinema & Television', emoji: '\ud83c\udf7f', desc: 'Binge-watching, classic films, and directing styles.', questions: ['Will the "binge-watching" distribution model ultimately destroy the cultural impact and communal theory-crafting of the weekly television release?', 'Does the reliance on massive IP franchises and nostalgia-bait signify that Hollywood has run out of ideas, or just that audiences are terrified of the unfamiliar?', 'How much does knowing the toxic or controversial off-screen behavior of an actor permanently alter how you experience their on-screen performance?'] },
      { id: 'music-concerts', name: 'Music & Concerts', emoji: '\ud83c\udfb8', desc: 'Vinyl collecting, music production, and live festivals.', questions: ['Does the pursuit of flawless, pitch-corrected studio perfection strip away the raw, emotional human vulnerability that makes music resonate?', 'Why does the music we listen to between the ages of 13 and 16 imprint so permanently on our brains compared to anything we discover later in life?', 'Is the modern concert experience ruined by thousands of glowing smartphones, or is capturing the moment just a new way of experiencing it?'] },
      { id: 'photography', name: 'Photography', emoji: '\ud83d\udcf7', desc: 'Film vs. digital, street photography, and editing techniques.', questions: ['In an age where literally everyone has a high-resolution, AI-assisted camera in their pocket, what actually separates a hobbyist from a true "photographer"?', 'Does the act of constantly taking photos to document an experience prevent you from actually being mentally present for it?', 'As AI image generation becomes photorealistic, will the raw, unedited, slightly blurry photograph become the new standard of high art?'] },
      { id: 'theater', name: 'Theater & Performing Arts', emoji: '\ud83c\udfad', desc: 'Broadway, stand-up comedy, and improv.', questions: ['What specific, visceral energy exists in live theater that makes a minor mistake on stage thrilling, whereas a mistake in a film ruins the immersion?', 'Has the skyrocketing cost of Broadway and West End tickets completely severed theater from its roots as art for the masses?', 'How does the strict etiquette of sitting silently in a dark theater change the way we absorb art compared to the interactive nature of a concert or gallery?'] },
      { id: 'design-architecture', name: 'Design & Architecture', emoji: '\ud83c\udfdb\ufe0f', desc: 'Interior design, brutalism, and city planning.', questions: ['Does the modern obsession with stark, minimalist architecture strip cities of their cultural soul, or does it provide necessary visual calm?', 'Is "hostile architecture" (like spikes on ledges or slanted benches) a necessary tool for urban order, or a cruel reflection of a society\'s lack of empathy?', 'Should a building\'s form strictly follow its function, or does architecture have a duty to prioritize aesthetic beauty even if it\'s impractical?'] },
    ],
  },
  {
    id: 'hobbies',
    name: 'Hobbies & Crafting',
    emoji: '\ud83e\udde9',
    subtopics: [
      { id: 'board-games', name: 'Tabletop & Board Games', emoji: '\ud83c\udfb2', desc: 'D&D, strategy games, and party games.', questions: ['Is the massive renaissance of complex, physical board games a direct psychological rebellion against our screen-dominated daily lives?', 'In a highly strategic, cooperative board game, how do you prevent the "alpha gamer" from simply playing everyone else\'s turns for them?', 'Does the reliance on literal dice rolls (RNG) in a game mimic the unfairness of real life, or is it just a crutch for bad game design?'] },
      { id: 'textile-arts', name: 'Textile Arts', emoji: '\ud83e\uddf6', desc: 'Knitting, crocheting, sewing, and fashion design.', questions: ['Does the slow, deliberate, and often tedious nature of knitting or sewing provide a meditative antidote to the instant gratification of modern consumerism?', 'How has the rise of ultra-fast fashion devalued the public\'s understanding of the incredible skill and labor required to make a single garment?', 'Why is there such a profound psychological difference between wearing something you bought and wearing something you made with your own hands?'] },
      { id: 'diy-woodworking', name: 'DIY & Woodworking', emoji: '\ud83d\udd28', desc: 'Restoring furniture, home renovations, and tools.', questions: ['Does the "IKEA effect"—loving something more simply because you assembled it—prove that humans inherently crave the struggle of creation?', 'In woodworking, is true mastery knowing how to execute a perfectly flawless joint, or knowing how to elegantly hide your inevitable mistakes?', 'As society pushes further into the digital realm, will the ability to build and fix physical objects with our hands become a lost art or a premium luxury?'] },
      { id: 'gardening', name: 'Gardening', emoji: '\ud83c\udf31', desc: 'Houseplants, urban farming, and landscaping.', questions: ['Is gardening an act of harmonizing with nature, or is it actually an act of supreme control and defiance against the natural order of chaos?', 'How does the simple act of keeping a difficult houseplant alive fulfill the primal human need for nurturing and routine?', 'Should we prioritize planting aesthetically pleasing, exotic flowers, or strictly focus on native plants that support local ecosystems, even if they look like weeds?'] },
      { id: 'automotive', name: 'Automotive', emoji: '\ud83c\udfce\ufe0f', desc: 'Classic car restoration, Formula 1, and EVs.', questions: ['Does the transition from internal combustion engines to silent, highly efficient electric vehicles strip a car of its mechanical "soul"?', 'As cars become rolling supercomputers, are we sacrificing the fundamental human freedom of the "open road" for the convenience of autonomous safety?', 'Why do classic, objectively less safe, and unreliable vintage cars evoke such intense passion compared to flawless modern vehicles?'] },
    ],
  },
  {
    id: 'science-nature',
    name: 'Science & Nature',
    emoji: '\ud83e\udde0',
    subtopics: [
      { id: 'astronomy', name: 'Astronomy & The Cosmos', emoji: '\ud83d\udd2d', desc: 'Black holes, exoplanets, and the Fermi Paradox.', questions: ['Does gazing at the unfathomable scale of the universe trigger a feeling of liberating insignificance, or a sense of terrifying existential dread?', 'If humanity fully maps the cosmos and proves the multiverse is real, will our day-to-day squabbles on Earth seem more absurd, or remain exactly the same?', 'What is the philosophical impact of realizing that every time we look at a distant star, we are literally looking thousands of years into the past?'] },
      { id: 'biology-genetics', name: 'Biology & Genetics', emoji: '\ud83e\uddec', desc: 'CRISPR, de-extinction, and human evolution.', questions: ['If CRISPR technology allows us to perfectly edit out all genetic diseases, at what point does it cross the line into highly unethical eugenics?', 'What actually defines a "species" if the boundaries of DNA are constantly shifting, blurring, and mutating over time?', 'Should we use genetic engineering to resurrect extinct animals (like the woolly mammoth), or is that an arrogant disruption of natural selection?'] },
      { id: 'natural-world', name: 'The Natural World', emoji: '\ud83c\udf0b', desc: 'Deep ocean, extreme weather, and bizarre plant life.', questions: ['If modern science proves that trees communicate and share resources through complex underground fungal networks, does that mean forests have a form of consciousness?', 'Are humans the custodians of the natural world, or simply a highly destructive, invasive species that the Earth will eventually course-correct?', 'Does viewing nature strictly as a "resource" to be managed inevitably lead to its destruction, regardless of how sustainable our methods are?'] },
      { id: 'animal-behavior', name: 'Animal Behavior', emoji: '\ud83d\udc3e', desc: 'Animal intelligence, pet psychology, and conservation.', questions: ['How much of what we perceive as "love" or "guilt" in our pets is genuine emotion, versus us projecting complex human psychology onto survival instincts?', 'If we discover that certain animals possess language, culture, and self-awareness, does our entire moral framework regarding meat consumption collapse?', 'Is true altruism—sacrificing oneself for another without evolutionary benefit—unique to humans, or does it exist in the wild?'] },
      { id: 'neuroscience', name: 'Neuroscience', emoji: '\ud83e\udde0', desc: 'Memory, dreaming, and neuroplasticity.', questions: ['If all of our thoughts, loves, and fears can be reduced to electrical impulses and chemical reactions in the brain, does "free will" actually exist?', 'Can we ever solve the "hard problem" of consciousness, or is a brain trying to understand its own consciousness fundamentally impossible?', 'If we develop the technology to selectively erase traumatic memories, would using it destroy the very experiences that shape our character?'] },
    ],
  },
  {
    id: 'history-mythology',
    name: 'History & Mythology',
    emoji: '\ud83c\udfdb\ufe0f',
    subtopics: [
      { id: 'ancient-civs', name: 'Ancient Civilizations', emoji: '\ud83c\udffa', desc: 'Everyday life in Rome, Pyramids, and lost cities.', questions: ['If history is almost exclusively written by the victors, how much of what we consider "ancient fact" is actually just highly successful state propaganda?', 'Does our modern assumption that ancient people were less intelligent prevent us from understanding the true ingenuity of their lost technologies?', 'Are the rise and fall of civilizations a linear progression of progress, or a doomed, repeating cycle of hubris and collapse?'] },
      { id: 'modern-history', name: 'Modern History & Espionage', emoji: '\ud83d\udd75\ufe0f\u200d\u2642\ufe0f', desc: 'Cold War spy tactics, codebreaking, and famous heists.', questions: ['How heavily is our daily, mundane reality shaped by covert intelligence operations and classified secrets that we will never know about?', 'Will the digital age make espionage impossible due to constant surveillance, or easier due to the vulnerabilities of cyber infrastructure?', 'Looking back at the Cold War, did the threat of mutually assured destruction actually save humanity, or just permanently traumatize our collective psyche?'] },
      { id: 'mythology', name: 'Mythology & Folklore', emoji: '\ud83d\udc09', desc: 'Greek and Norse gods, urban legends, and cryptids.', questions: ['Why do almost all disconnected ancient cultures share identical core myths, such as the great flood or the hero\'s journey?', 'Are the flawed, petty, and deeply human gods of Greek and Norse mythology more comforting than the concept of an omnipotent, flawless creator?', 'What are the modern-day equivalents of folklore and myth that future historians will look back on as our society\'s core belief systems?'] },
      { id: 'alternate-history', name: 'Alternate History', emoji: '\ud83d\udd70\ufe0f', desc: 'What-if scenarios that reshape the world.', questions: ['Is the trajectory of history driven by the sheer will of "Great Men," or are massive historical shifts inevitable due to shifting socioeconomic tides?', 'If you could change one incredibly minor, seemingly insignificant historical event, what would have the most catastrophic butterfly effect on the present?', 'Why is the human mind so fascinated with "what if" scenarios regarding tragic events—is it a way to process grief or an illusion of control?'] },
      { id: 'weird-history', name: 'Weird History', emoji: '\ud83d\udcdc', desc: 'Bizarre fashion, strange medicine, and forgotten figures.', questions: ['What does the history of bizarre mass hysterias (like the Dancing Plague) teach us about the extreme fragility of the human mind under stress?', 'How many world-changing geniuses and inventors were entirely lost to history simply because they were born in the wrong geographic location or social class?', 'Looking back at bizarre historical medical fads, what highly normalized medical or lifestyle practices today will seem utterly barbaric in 200 years?'] },
    ],
  },
  {
    id: 'philosophy',
    name: 'Philosophy & Deep Thoughts',
    emoji: '\ud83d\udca1',
    subtopics: [
      { id: 'ethics', name: 'Ethics & Morality', emoji: '\u2696\ufe0f', desc: 'The Trolley Problem, cloning, and utilitarianism.', questions: ['If a self-driving car must choose between hitting a pedestrian or crashing and killing its own passenger, whose ethics should it be programmed to follow?', 'Is morality an objective truth woven into the fabric of the universe, or just a highly evolved, mutually beneficial social contract between primates?', 'Does true altruism exist, or is every "selfless" act ultimately driven by a selfish desire to feel good about ourselves or secure social standing?'] },
      { id: 'existentialism', name: 'Existentialism & Reality', emoji: '\ud83c\udf0c', desc: 'Simulation theory, meaning of life, and free will.', questions: ['Is the realization that the universe is inherently meaningless a deeply depressing truth, or the most liberating concept humans can grasp?', 'If we are living in a highly advanced, flawlessly executed computer simulation, does that actually change how we should live our daily lives?', 'Is the ultimate burden of being human the terrifying, absolute freedom to choose our own path without any inherent roadmap?'] },
      { id: 'psychology', name: 'Human Psychology', emoji: '\ud83e\udde0', desc: 'Cognitive biases, happiness, and nature vs. nurture.', questions: ['What defines your "true self": the unfiltered thoughts inside your head that you hide, or the curated actions and behaviors you show to the world?', 'Are dark triad traits (narcissism, Machiavellianism, psychopathy) evolutionary defects, or highly adaptive survival strategies in modern corporate society?', 'How much of our personality is an authentic, core identity, and how much is just a patchwork of coping mechanisms developed in childhood?'] },
      { id: 'time', name: 'The Concept of Time', emoji: '\u23f3', desc: 'Time travel paradoxes and the butterfly effect.', questions: ['Does the past still exist somewhere in the fabric of spacetime, or is the fleeting, razor-thin present moment the only thing that is objectively real?', 'Why does our internal perception of time accelerate so drastically as we age, and is it possible to consciously slow it down?', 'If time travel to the past were possible, would the universe instantly course-correct any paradoxes, or would it fracture into infinite, branching realities?'] },
    ],
  },
  {
    id: 'finance',
    name: 'Finance & Economics',
    emoji: '\ud83d\udcb0',
    subtopics: [
      { id: 'personal-finance', name: 'Personal Finance', emoji: '\ud83d\udcb5', desc: 'FIRE movement, frugality, and budgeting hacks.', questions: ['How much of our stress about money is driven by actual survival needs, versus the psychological trap of constantly comparing our lifestyle to others?', 'Does the extreme frugality required by the FIRE (Financial Independence, Retire Early) movement rob you of the best years of your life to secure an uncertain future?', 'Is debt a necessary tool for modern social mobility, or a masterfully designed system to keep the working class permanently indentured?'] },
      { id: 'investing', name: 'Investing Strategies', emoji: '\ud83d\udcc8', desc: 'Real estate, stock market, and crypto.', questions: ['If the Efficient Market Hypothesis is true and all information is already priced in, is active stock picking basically just high-stakes astrology for finance bros?', 'Does the underlying philosophy of cryptocurrency represent the ultimate liberation from government control, or the hyper-financialization of every aspect of life?', 'Is the massive, passive flow of trillions of dollars into index funds distorting the reality of the stock market and destroying price discovery?'] },
      { id: 'global-economics', name: 'Global Economics', emoji: '\ud83c\udf0d', desc: 'UBI, inflation, and the diamond industry.', questions: ['Is the concept of infinite, quarter-over-quarter economic growth fundamentally incompatible with the reality of living on a planet with finite resources?', 'If a Universal Basic Income (UBI) covered all survival needs, would society collapse into laziness, or experience an unprecedented renaissance of art and innovation?', 'How does the complete abstraction of money—from physical gold to digital numbers on a screen—change our psychological relationship with value?'] },
      { id: 'behavioral-econ', name: 'Behavioral Economics', emoji: '\ud83d\uded2', desc: 'How stores trick you and psychology of marketing.', questions: ['Why do highly intelligent people consistently fall victim to the sunk-cost fallacy, holding onto plummeting investments or toxic relationships?', 'Is the concept of a "rational consumer" an utter myth invented by economists who refuse to acknowledge how emotionally driven human behavior actually is?', 'How heavily is our perception of a product\'s quality manipulated simply by placing a higher price tag on it?'] },
    ],
  },
  {
    id: 'relationships',
    name: 'Relationships & Society',
    emoji: '\ud83e\udd1d',
    subtopics: [
      { id: 'modern-dating', name: 'Modern Dating', emoji: '\ud83d\udc98', desc: 'Dating apps, green/red flags, and LDRs.', questions: ['Has the illusion of infinite choice provided by dating apps completely destroyed our ability to commit and work through normal relationship friction?', 'Do highly specific algorithms match us with truly compatible partners, or do they just match us with our own echo chambers, preventing growth?', 'Is the "spark" we look for on a first date an indicator of true love, or just a spike in anxiety and familiar attachment trauma?'] },
      { id: 'friendship', name: 'Friendship Dynamics', emoji: '\ud83c\udf7b', desc: 'Making friends as an adult and chosen family.', questions: ['Why does society highly ritualize and validate romantic heartbreak, but offer almost no framework for grieving the agonizing end of a platonic friendship?', 'Is the "Dunbar Number" (the theory that humans can only maintain ~150 stable relationships) breaking our brains in an era of thousands of social media followers?', 'As adults, is it actually harder to make new friends, or have our standards for vulnerability and shared time simply become too rigid?'] },
      { id: 'generational', name: 'Generational Shifts', emoji: '\ud83d\udd04', desc: 'Gen Z vs. Millennials and the nostalgia cycle.', questions: ['Is the current animosity between Boomers, Millennials, and Gen Z unique to our economic time, or just the exact same generational cycle of resentment playing out again?', 'Will the unprecedented transfer of wealth (or lack thereof) in the coming decades fundamentally break the traditional milestones of adulthood?', 'How will growing up entirely documented on the internet from birth change the core psychology of the incoming generation?'] },
      { id: 'societal-norms', name: 'Societal Norms', emoji: '\ud83d\udde3\ufe0f', desc: 'Evolution of manners, cancel culture, and influencers.', questions: ['Does "cancel culture" represent a necessary democratization of accountability, or a terrifying return to the puritanical mob justice of the village square?', 'What completely normal, everyday societal expectation of the 2020s will be viewed as deeply toxic or unhinged by the year 2070?', 'Has the modern hyper-focus on individualism and personal boundaries completely eroded our sense of duty and obligation to our communities?'] },
    ],
  },
  {
    id: 'fashion',
    name: 'Fashion & Aesthetics',
    emoji: '\ud83d\udc57',
    subtopics: [
      { id: 'streetwear', name: 'Streetwear & Sneaker Culture', emoji: '\ud83d\udc5f', desc: 'Psychology of hype, sneaker collecting, and vintage.', questions: ['At what point did streetwear transition from a raw, anti-establishment counterculture into the ultimate symbol of hyper-capitalist status?', 'Does the multi-billion dollar secondary resale market for sneakers celebrate the design, or entirely ruin the joy of actually wearing the shoes?', 'Is manufactured scarcity (the "drop" model) a brilliant marketing tactic, or deeply manipulative to consumer psychology?'] },
      { id: 'sustainable-fashion', name: 'Sustainable Fashion', emoji: '\u267b\ufe0f', desc: 'Fast fashion impact, upcycling, and capsule wardrobes.', questions: ['Can any massive, global fashion brand truly be considered "sustainable," or is "greenwashing" just a way to sell us more products guilt-free?', 'How do we balance the immense environmental cost of "fast fashion" with the reality that it allows lower-income individuals to participate in modern trends?', 'If a single garment lasts a lifetime, are we prepared to abandon the psychological dopamine hit of buying something new?'] },
      { id: 'high-fashion', name: 'High Fashion & History', emoji: '\ud83d\udc60', desc: 'Iconic runway moments and the Met Gala.', questions: ['Is avant-garde high fashion a legitimate, wearable art form, or an exclusive inside joke meant to separate the ultra-wealthy from the working class?', 'How profoundly does the "trickle-down" effect of haute couture silently dictate the mundane clothing choices of people who claim to not care about fashion?', 'Has the fashion industry genuinely improved its toxic standards regarding body image, or has the aesthetic of "inclusivity" just become a trendy marketing tool?'] },
      { id: 'personal-style', name: 'Personal Style', emoji: '\u2728', desc: 'Color seasons, signature scents, and identity.', questions: ['Is your personal style a true reflection of your inner identity, or simply a curated uniform signaling which socioeconomic tribe you want to belong to?', 'Does adhering to a strict "personal uniform" (like Steve Jobs\' turtleneck) liberate your mind from decision fatigue, or stifle your daily creativity?', 'Why is it so deeply uncomfortable to step outside in an outfit that feels inauthentic to who we believe we are?'] },
    ],
  },
  {
    id: 'home-lifestyle',
    name: 'Home & Lifestyle',
    emoji: '\ud83c\udfe0',
    subtopics: [
      { id: 'design-philosophy', name: 'Design Philosophies', emoji: '\ud83d\udecb\ufe0f', desc: 'Minimalism vs. Maximalism and color psychology.', questions: ['Does extreme minimalism actually bring mental peace, or does it just create a sterile, highly stressful environment where every out-of-place object is a failure?', 'How heavily does the specific temperature and direction of lighting in a room dictate our subconscious emotional state?', 'Is the "open concept" floor plan a brilliant way to connect a family, or a terrible design that destroys all privacy and acoustic comfort?'] },
      { id: 'sustainable-living', name: 'Sustainable Living', emoji: '\ud83c\udf0d', desc: 'Zero-waste, off-grid, and tiny house movement.', questions: ['Is the burden of "zero waste" living unfairly placed on the individual consumer to distract from the massive pollution generated by a handful of mega-corporations?', 'What is the psychological appeal of romanticizing "off-grid" living in a society that has spent centuries innovating to escape the hardships of nature?', 'Can the aesthetic of "eco-friendly" products sometimes be more harmful to the environment than just buying less in the first place?'] },
      { id: 'daily-routines', name: 'Daily Routines', emoji: '\u2615', desc: 'Biohacking, morning routines, and sleep hygiene.', questions: ['Is the obsession with the highly optimized, 5:00 AM "billionaire morning routine" just a toxic byproduct of hustle culture?', 'How much of our daily exhaustion is physical tiredness versus profound "decision fatigue" from micromanaging modern life?', 'What is the critical difference between a rigid habit that traps you, and a meaningful ritual that grounds you?'] },
      { id: 'pet-culture', name: 'Pet Culture', emoji: '\ud83d\udc36', desc: 'Breeding ethics, exotic pets, and brain chemistry.', questions: ['Has elevating pets to the exact status of human children fundamentally changed our psychological relationship with animals for the better, or worse?', 'Is the selective breeding of animals for purely aesthetic traits (like flat-faced dogs) a form of normalized, generational animal abuse?', 'Why can humans easily compartmentalize the deep love for a pet dog, while simultaneously ignoring the ethical implications of the factory farming of pigs?'] },
    ],
  },
  {
    id: 'unexplained',
    name: 'The Unexplained & Mysticism',
    emoji: '\ud83d\udc7b',
    subtopics: [
      { id: 'paranormal', name: 'Paranormal Experiences', emoji: '\ud83c\udfe1', desc: 'Haunted locations, ghost hunting, and spooky stories.', questions: ['Why do almost all reported ghosts across history wear clothing—do inanimate objects like Victorian dresses also possess a spirit that haunts the afterlife?', 'Is the deep human fascination with the paranormal driven by a genuine search for truth, or a desperate psychological need to know death isn\'t the end?', 'Could what we call "hauntings" simply be complex physics we don\'t understand yet, like environmental recordings of high-emotion events?'] },
      { id: 'ufos', name: 'UFOs & UAPs', emoji: '\ud83d\udef8', desc: 'Declassified documents, Roswell, and close encounters.', questions: ['If major world governments suddenly confirmed the existence of extraterrestrial intelligence, would society actually panic, or just meme about it and go to work the next day?', 'Is the "Dark Forest Theory"—the idea that alien civilizations stay quiet to avoid being hunted—the most terrifying answer to the Fermi Paradox?', 'What if UFOs are not spacecraft from other planets, but interdimensional phenomena or future humans observing their own history?'] },
      { id: 'psych-mysteries', name: 'Psychological Mysteries', emoji: '\ud83c\udf00', desc: 'The Mandela Effect, d\u00e9j\u00e0 vu, and synchronicity.', questions: ['How is it possible that the placebo effect can actually heal physical ailments, and why can\'t we consciously harness that power at will?', 'What triggers mass psychogenic illness, where hundreds of people suddenly develop identical physical symptoms with no biological cause?', 'Are cryptids (like Bigfoot or the Loch Ness Monster) physical creatures, or deep-seated archetypal projections of our fear of the untamed wilderness?'] },
      { id: 'astrology', name: 'Astrology & Divination', emoji: '\ud83d\udd2e', desc: 'Birth charts, tarot cards, and horoscopes.', questions: ['Does the immense popularity of astrology in the modern era represent a failure of organized religion to provide comfort and structure?', 'Is reading a tarot deck actually tapping into mystical energy, or is it just a brilliant psychological tool for bypassing the conscious mind and exploring our own intuition?', 'How much of a horoscope\'s accuracy relies entirely on confirmation bias and the Barnum effect?'] },
    ],
  },
  {
    id: 'education',
    name: 'Education & Learning',
    emoji: '\ud83c\udf93',
    subtopics: [
      { id: 'alt-schooling', name: 'Alternative Schooling', emoji: '\ud83c\udfeb', desc: 'Homeschooling, Montessori, and unschooling.', questions: ['Does "unschooling" create incredibly independent, self-motivated thinkers, or does it severely handicap a child\'s ability to function in a structured, deadline-driven society?', 'Is the Montessori method truly revolutionary, or has it just become a gated, expensive aesthetic for privileged parents?', 'By removing traditional grading and standardized tests, do we foster true learning, or do we remove the necessary friction that builds resilience?'] },
      { id: 'languages', name: 'Language Acquisition', emoji: '\ud83d\udde3\ufe0f', desc: 'Immersion, hardest languages, and conlangs.', questions: ['Does the Sapir-Whorf hypothesis hold true—does the language you speak actually dictate and limit the thoughts you are capable of having?', 'If AI earpieces can flawlessly translate any language in real-time, will the immense cognitive and cultural effort of learning a second language become obsolete?', 'When a minor, indigenous language dies out, what exactly is lost that cannot be preserved in a museum or a dictionary?'] },
      { id: 'higher-ed', name: 'The Future of Higher Ed', emoji: '\ud83d\udcdc', desc: 'Is a degree still worth it? Trade schools and prestige.', questions: ['Has the modern university transitioned from a sanctuary of higher learning into a predatory hedge fund that sells overpriced credentials?', 'Will the stigma against dropping out or bypassing college entirely vanish as self-taught, portfolio-driven careers become the norm?', 'Should a society strictly prioritize funding STEM fields for technological advancement, or are the humanities crucial to ensuring we don\'t destroy ourselves with that tech?'] },
      { id: 'lifelong-learning', name: 'Lifelong Learning', emoji: '\ud83e\udde0', desc: 'New skills as an adult, MasterClass, and YouTube.', questions: ['Why does society attach such a heavy stigma to being a "beginner" at something in adulthood, compared to the grace we give children?', 'With infinite information available instantly on the internet, why is the general population arguably more misinformed and easily manipulated than ever?', 'How does the physical structure of the adult brain (neuroplasticity) change when we force ourselves to learn a complex new skill, like an instrument, at age 50?'] },
      { id: 'memory', name: 'Memory & Cognition', emoji: '\ud83e\udde9', desc: 'Memory palaces, spaced repetition, and speed-reading.', questions: ['By constantly outsourcing our memory to smartphones, GPS, and search engines, are we fundamentally degrading the evolutionary capacity of our brains?', 'How terrifying is the proven psychological fact that eyewitness accounts are incredibly unreliable and that our memories alter slightly every time we recall them?', 'Could teaching ancient mnemonic techniques, like the "Memory Palace," revolutionize how we absorb information in the modern digital age?'] },
    ],
  },
  {
    id: 'internet-culture',
    name: 'Internet Culture',
    emoji: '\ud83c\udf10',
    subtopics: [
      { id: 'viral', name: 'Viral Dynamics', emoji: '\ud83d\udcc8', desc: 'Meme life cycles, algorithms, and TikTok challenges.', questions: ['Is virality truly organic, or is it entirely engineered by opaque algorithms designed to exploit human outrage and dopamine loops?', 'What is the psychological toll of achieving sudden, massive internet fame by accident, only to be entirely forgotten three days later?', 'Have memes evolved from simple internet jokes into a highly sophisticated, abstract language capable of conveying complex political and existential thought?'] },
      { id: 'content-creation', name: 'Content Creation', emoji: '\ud83c\udfa5', desc: 'YouTube, Twitch streaming, and influencer burnout.', questions: ['Does the demand for constant "authenticity" from creators inherently turn their actual private lives into a performative, commodified product?', 'How will the normalization of parasocial relationships—feeling a deep, one-sided bond with an influencer—change the way we approach real-world friendships?', 'Is the "creator economy" a liberation from the 9-to-5, or just a deeply precarious gig economy wrapped in a ring light?'] },
      { id: 'online-communities', name: 'Niche Online Communities', emoji: '\ud83d\udc7e', desc: 'Reddit lore, rabbit holes, and extreme fandoms.', questions: ['Do hyper-niche online communities provide vital safe havens for marginalized interests, or do they inevitably devolve into toxic, radicalized echo chambers?', 'Does gatekeeping a niche hobby preserve its core culture, or is it just an expression of elitism that kills the community\'s growth?', 'How has the democratization of fandom changed the relationship between creators and their audiences, for better or worse?'] },
      { id: 'digital-privacy', name: 'Digital Privacy', emoji: '\ud83d\udd12', desc: 'Digital footprints, Dead Internet theory, and ads.', questions: ['Is the argument "I have nothing to hide" a valid reason to surrender data, or a fundamental misunderstanding of why privacy is a human right?', 'When companies offer free services in exchange for our data, have we unknowingly accepted a system where our behavioral profiles are the actual product?', 'Will the "right to be forgotten"—the ability to completely scrub your past from the internet—become the most highly contested civil right of the 21st century?'] },
      { id: 'cybersecurity', name: 'Cybersecurity & Hacking', emoji: '\ud83d\udcbb', desc: 'Social engineering, data breaches, and the dark web.', questions: ['As our physical infrastructure (power grids, water, hospitals) becomes entirely networked, is a catastrophic cyber-war inevitable?', 'Is the line between an "ethical hacker" and a cybercriminal defined purely by intent, or is the act of breaching a system inherently destabilizing?', 'Will the arms race between AI-generated phishing attacks and AI-driven cybersecurity make human intuition entirely irrelevant in protecting our data?'] },
    ],
  },
  {
    id: 'mental-health',
    name: 'Mental Health & Wellness',
    emoji: '\ud83e\uddd8',
    subtopics: [
      { id: 'therapy', name: 'Therapy & Counseling', emoji: '\ud83d\udecb\ufe0f', desc: 'CBT, EMDR, and breaking the stigma.', questions: ['Has the widespread adoption of "therapy speak" in daily life (like casually diagnosing friends as toxic or narcissistic) actually diluted the meaning of serious clinical terms?', 'Is the goal of modern therapy to help us adjust to a profoundly sick, hyper-capitalist society, or to help us realize the society is the problem?', 'How do you balance the necessity of validating someone\'s trauma with the danger of letting that trauma become their entire, permanent identity?'] },
      { id: 'mindfulness', name: 'Mindfulness in Practice', emoji: '\ud83c\udf3f', desc: 'Breathwork, sound baths, and Vipassana retreats.', questions: ['Has "McMindfulness"—the corporate commodification of meditation—stripped an ancient spiritual practice of its ethics to just make us more productive workers?', 'Is it actually possible to remain fully mentally present in a society designed by thousands of engineers to hijack our attention every three seconds?', 'Does the constant pursuit of inner peace sometimes turn into "spiritual bypassing," where we use zen to avoid dealing with real-world injustices?'] },
      { id: 'emotional-iq', name: 'Emotional Intelligence', emoji: '\u2764\ufe0f', desc: 'Attachment styles, shadow work, and boundaries.', questions: ['Can true empathy actually be taught in adulthood, or is it a trait that must be fundamentally wired in early childhood?', 'When corporations emphasize EQ in leadership, are they looking for genuine compassion, or just the ability to expertly manipulate employee morale?', 'Is it possible to be overly empathetic, to the point where absorbing the emotions of others severely damages your own psychological survival?'] },
      { id: 'alt-therapies', name: 'Alternative Therapies', emoji: '\ud83c\udfa8', desc: 'Music therapy, art therapy, and equine therapy.', questions: ['As psychedelics (like psilocybin) enter mainstream therapy, do we risk losing their profound mystical elements by sanitizing them into a clinical, pharmaceutical model?', 'How much of the healing power of alternative therapies (crystals, sound baths, reiki) is just the incredible, biological power of the placebo effect?', 'Is the mind-body connection powerful enough that unaddressed, repressed emotional trauma can literally manifest as chronic physical illness?'] },
      { id: 'stress', name: 'Stress Mechanics', emoji: '\ud83d\udc86', desc: 'Chronic stress, ASMR, and coping mechanisms.', questions: ['Is our modern, constant baseline of low-level anxiety actually more biologically damaging than the short, intense bursts of life-or-death stress our ancestors faced?', 'Can we consciously reframe "distress" into "eustress" (positive, motivating stress) just by changing our internal narrative about the pressure we face?', 'Are we raising a generation that is actually addicted to cortisol, unable to tolerate silence or peace without feeling profoundly under-stimulated?'] },
    ],
  },
  {
    id: 'transportation',
    name: 'Transportation & Mobility',
    emoji: '\ud83d\ude97',
    subtopics: [
      { id: 'urban-transit', name: 'Urban Transit', emoji: '\ud83d\ude87', desc: '15-minute cities, high-speed rail, and subways.', questions: ['Does prioritizing car-centric infrastructure inherently destroy the cultural and economic soul of a city by preventing spontaneous human interaction?', 'If public transportation was made completely free worldwide, would it solve the climate crisis, or would the systems collapse under the strain of maintenance?', 'Is the concept of the "15-minute city" a utopian vision for community living, or an unintentional blueprint for deeply segregated neighborhoods?'] },
      { id: 'aviation', name: 'Aviation & Aerospace', emoji: '\u2708\ufe0f', desc: 'Becoming a pilot, disasters, and supersonic flight.', questions: ['How does the sheer miracle of flying 30,000 feet in the air become completely overshadowed by our annoyance at legroom and baggage fees?', 'As the environmental cost of flying becomes undeniable, will long-haul travel revert to being an exclusive luxury only the ultra-wealthy can ethically afford?', 'What is the specific psychology of airports that makes time, diet, and social norms completely cease to exist once you pass security?'] },
      { id: 'auto-future', name: 'The Automotive Future', emoji: '\ud83d\udd0b', desc: 'Self-driving cars, hydrogen vs. electric, and manuals.', questions: ['If fully autonomous vehicles eliminate traffic and accidents, will we eventually criminalize human driving on public roads as a reckless danger?', 'Will the end of private car ownership in favor of subscription-based ride-hailing destroy the independence that the automobile historically represented?', 'How do we program the ethics of a self-driving car when it must make a split-second decision between the life of its occupant and a bystander?'] },
      { id: 'micromobility', name: 'Micromobility', emoji: '\ud83d\udef4', desc: 'E-bikes, scooters, and urban infrastructure.', questions: ['Have electric scooters and e-bikes actually revolutionized the "last mile" of urban transit, or just created hazardous clutter on our sidewalks?', 'How do we safely integrate vehicles that move too fast for the pedestrian sidewalk, but too slow for the main road, into cities built 100 years ago?', 'Is micromobility the great equalizer of urban transport, or does it disproportionately cater to young, able-bodied professionals?'] },
      { id: 'maritime', name: 'Maritime Logistics', emoji: '\ud83d\udea2', desc: 'Megaships, cargo freighters, and global shipping.', questions: ['How is it that the massive ocean shipping industry, which single-handedly sustains global modern civilization, remains almost entirely invisible to the average consumer?', 'Do "flags of convenience" allow shipping companies to operate in a lawless, unregulated void that exploits workers and destroys the oceans?', 'If a single ship blocking a canal can cripple the global economy, is our pursuit of hyper-efficient "just-in-time" supply chains a catastrophic vulnerability?'] },
    ],
  },
  {
    id: 'humor',
    name: 'Humor & Comedy',
    emoji: '\ud83c\udfad',
    subtopics: [
      { id: 'standup', name: 'Stand-up Culture', emoji: '\ud83c\udfa4', desc: 'Evolution of stand-up and writing a tight five.', questions: ['Is the primary role of the stand-up comedian to be a modern philosopher speaking truth to power, or is it fundamentally just to get the laugh, no matter what?', 'Does the concept of "punching up" vs. "punching down" limit the artistic freedom of comedy, or does it provide a necessary ethical framework for satire?', 'How has the internet\'s ability to pull a single joke out of a two-hour context destroyed the nuanced art of building a complex comedy set?'] },
      { id: 'satire', name: 'Satire & Parody', emoji: '\ud83e\udd21', desc: 'The Onion, satirical news, and spoof movies.', questions: ['In an era where actual political headlines are deeply absurd, has reality officially outpaced our ability to write effective satire?', 'Does highly effective political parody actually change minds, or does it just serve as a pressure valve that lets the opposing side laugh and do nothing?', 'At what point does post-ironic humor become entirely indistinguishable from the actual terrible beliefs it is supposed to be mocking?'] },
      { id: 'dark-comedy', name: 'Dark & Taboo Comedy', emoji: '\ud83d\udc80', desc: 'Where is the line? Morbid humor as coping.', questions: ['Is laughing at profound trauma and tragedy the ultimate human defense mechanism against despair, or a sign of societal sociopathy?', 'Why is a joke about death wildly offensive to one grieving person, but the exact thing that allows another grieving person to finally breathe?', 'If there is no topic that should be strictly off-limits in comedy, how do we distinguish between an edgy joke and genuine hate speech disguised as humor?'] },
      { id: 'improv', name: 'Improv & Sketch', emoji: '\ud83c\udfac', desc: 'The Yes-and philosophy and the history of SNL.', questions: ['Can the core rule of improv—"Yes, and..."—be applied to our daily lives as a radical philosophy for better communication and empathy?', 'Why is watching an improv scene fail spectacularly sometimes more entertaining and endearing than watching a perfectly executed script?', 'Does sketch comedy capture the zeitgeist of a specific decade better than dramatic film or literature?'] },
      { id: 'global-humor', name: 'Global Humor', emoji: '\ud83c\udf0d', desc: 'Lost in translation: British dry wit vs. slapstick.', questions: ['Why is humor arguably the absolute hardest thing to translate across languages, even when the literal words are translated perfectly?', 'Does understanding what a foreign culture finds taboo or hilarious give you a deeper understanding of their history than reading a textbook?', 'Is physical, slapstick comedy the only truly universal language, or are there conceptual jokes that every human on earth inherently understands?'] },
    ],
  },
  {
    id: 'social-impact',
    name: 'Social Impact & Activism',
    emoji: '\ud83c\udf0d',
    subtopics: [
      { id: 'environmentalism', name: 'Modern Environmentalism', emoji: '\ud83c\udf31', desc: 'Ocean cleanup, carbon offsetting, and greenwashing.', questions: ['Was the concept of the "personal carbon footprint" a brilliant corporate PR campaign designed to shift the guilt of climate change from mega-polluters to individual citizens?', 'Does apocalyptic climate messaging actually motivate the public to take action, or does it induce a state of paralyzed, nihilistic despair?', 'Where is the ethical line drawn between radical, necessary protest (like blocking traffic or throwing soup on art) and actions that just alienate the working class?'] },
      { id: 'community-action', name: 'Community Action', emoji: '\ud83e\udd1d', desc: 'Mutual aid, community fridges, and Peace Corps.', questions: ['Is mutual aid a more pure and effective form of helping your neighbors than relying on massive, bureaucratic charity organizations?', 'How do you improve and invest in a neglected neighborhood without inherently triggering the gentrification that forces the original community out?', 'Does social media "slacktivism" (reposting infographics) actually raise awareness, or does it just provide a false sense of accomplishment that replaces real-world organizing?'] },
      { id: 'human-rights', name: 'Human Rights Debates', emoji: '\u2696\ufe0f', desc: 'Wealth inequality, free speech, and accessibility.', questions: ['Is the concept of "universal human rights" an objective truth, or a Western construct being imposed on cultures with entirely different historical moral frameworks?', 'Will access to the unfiltered internet be universally recognized as a fundamental human right, or is it a luxury we can live without?', 'Does the United Nations possess actual power to protect human rights, or is it merely a theatrical forum for global posturing?'] },
      { id: 'philanthropy', name: 'Philanthropy & Giving', emoji: '\ud83d\udcb8', desc: 'Effective Altruism, micro-lending, and billionaires.', questions: ['Should billionaires exist and be allowed to dictate global policy through their massive philanthropic foundations, or is that a failure of wealth taxation?', 'Does the "Effective Altruism" movement strip the humanity and empathy out of charity by reducing human suffering to a cold, mathematical spreadsheet?', 'Why are we so obsessed with the "overhead myth" (demanding charities spend 0% on administration) when we know talented leadership and infrastructure require money to succeed?'] },
      { id: 'animal-rights', name: 'Animal Rights', emoji: '\ud83d\udc3e', desc: 'Factory farming, animal testing, and the ivory trade.', questions: ['Is "speciesism"—the assumption of human superiority leading to the exploitation of animals—the next massive moral blind spot future generations will judge us for?', 'Can the existence of modern zoos be ethically justified under the banner of conservation and education, or are they fundamentally just prisons for entertainment?', 'If lab-grown meat becomes completely indistinguishable from real meat and economically viable, will the traditional slaughter of animals be globally outlawed?'] },
    ],
  },
  {
    id: 'survival',
    name: 'Survival & Bushcraft',
    emoji: '\ud83c\udfd5\ufe0f',
    subtopics: [
      { id: 'wilderness', name: 'Wilderness Survival', emoji: '\ud83c\udf32', desc: 'Foraging, building shelters, and water purification.', questions: ['In a life-or-death survival scenario, what breaks first: the physical limitations of the human body, or the psychological will to keep living?', 'Is our fascination with wilderness survival television driven by a genuine desire to learn, or a primal comfort in watching others suffer while we sit in a heated room?', 'Does stepping into the deep, untamed wilderness expose the absolute illusion of control that modern society gives us?'] },
      { id: 'doomsday', name: 'Prep & Doomsday', emoji: '\ud83c\udf92', desc: 'Bug-out bags, bunkers, and EMP preparation.', questions: ['Is the modern "prepper" movement rooted in a logical assessment of fragile global supply chains, or a fear-based fantasy of becoming the hero in an apocalypse?', 'In a true societal collapse, would the lone-wolf survivalist with a bunker actually thrive, or would the people who prioritize building deep community networks survive longer?', 'Why do highly successful, wealthy individuals often spend millions preparing for the end of the world, rather than spending that money to prevent it?'] },
      { id: 'navigation', name: 'Old-World Navigation', emoji: '\ud83e\udded', desc: 'Orienteering, sextants, and topographical maps.', questions: ['By relying entirely on GPS to move through the world, have humans lost a fundamental, evolutionary connection to our spatial environment?', 'What is the profound psychological difference between "being lost" in a city without your phone, versus being lost in a dense forest?', 'Is there a therapeutic, grounding benefit to learning how to navigate by the stars and the sun, even if you never actually need to use it?'] },
      { id: 'first-aid', name: 'First Aid & Rescue', emoji: '\ud83d\ude91', desc: 'Wilderness medicine and search-and-rescue ops.', questions: ['How do you ethically process the harsh reality of triage in a mass-casualty scenario, where you must deliberately choose to let someone die to save others?', 'Does knowing advanced first aid make you a calmer person in daily life, or does it make you hyper-vigilant to the constant, fragile nature of the human body?', 'In a remote rescue situation, how much risk is a rescuer morally obligated to take on to save someone who made a completely reckless decision?'] },
      { id: 'primitive-skills', name: 'Primitive Skills', emoji: '\ud83d\udd25', desc: 'Friction fire, flint knapping, and trapping.', questions: ['Does the act of successfully starting a fire with nothing but friction tap into a deep, genetic memory that modern conveniences have suppressed?', 'Is the pursuit of bushcraft a rejection of modern technology, or just a profound appreciation for the ingenuity of our ancient ancestors?', 'Can mastering primitive, highly tactile skills cure the unique modern burnout that comes from staring at screens and moving digital data all day?'] },
    ],
  },
  {
    id: 'language-comm',
    name: 'Language & Communication',
    emoji: '\ud83d\udde3\ufe0f',
    subtopics: [
      { id: 'linguistics', name: 'Linguistics & Evolution', emoji: '\ud83d\udc12', desc: 'How languages change, dead languages, and swear word origins.', questions: ['Does the rapid evolution of internet slang, emojis, and textspeak represent the degradation of language, or the most efficient, hyper-evolved form of human communication yet?', 'Is Chomsky\'s theory of "Universal Grammar" correct—are humans born with a hardwired biological blueprint for language, or is it entirely learned?', 'How does the introduction of new words (like "doomscrolling" or "gaslighting") actually create new concepts in our collective consciousness that didn\'t exist before?'] },
      { id: 'nonverbal', name: 'Nonverbal Communication', emoji: '\ud83d\udc41\ufe0f', desc: 'Body language, micro-expressions, and cultural gestures.', questions: ['If 70% of human communication is nonverbal, how much profound nuance are we losing in a society that increasingly relies on text and emails?', 'Why are certain microexpressions (like the wrinkling of the nose in disgust) universally identical across every human culture on earth, including isolated tribes?', 'Is it actually possible to flawlessly detect deception through body language, or are we just punishing people for being nervous or neurodivergent?'] },
      { id: 'public-speaking', name: 'Public Speaking', emoji: '\ud83c\udfa4', desc: 'Stage fright, TED Talks, and debate tactics.', questions: ['Why does the human brain react to public speaking with the exact same life-or-death adrenaline response as being hunted by a predator?', 'In a highly successful speech, what matters more: the brilliant, logical structure of the content, or the raw, emotional charisma of the delivery?', 'How do the cadences, pauses, and rhythms of a great orator mirror the structure of a great piece of music?'] },
      { id: 'dialects', name: 'Dialects & Accents', emoji: '\ud83d\uddfa\ufe0f', desc: 'Regional slang, code-switching, and old Hollywood.', questions: ['Why do we inherently assign intelligence, trustworthiness, or humor to specific accents, and how does this linguistic prejudice impact society?', 'As the internet globalizes culture, are we slowly homogenizing toward one global accent, and what regional history dies when that happens?', 'Is "code-switching" (changing your dialect based on your environment) a brilliant social survival skill, or a tragic erasure of authentic identity?'] },
      { id: 'translation', name: 'The Art of Translation', emoji: '\ud83d\udcd6', desc: 'Translating poetry and AI vs. human nuance.', questions: ['When reading a translated masterpiece of literature, are you actually reading the original author, or are you just reading the translator\'s interpretation of them?', 'Are there truly "untranslatable" words that capture hyper-specific cultural emotions, or can any concept be explained with enough time?', 'Will AI ever be able to perfectly translate the nuance, cultural subtext, and humor of human speech, or will it always be entirely literal and hollow?'] },
    ],
  },
]

export function getTopicById(topicId) {
  return TOPICS.find((t) => t.id === topicId)
}

// Get subtopics across multiple topics
export function getSubtopicsForTopics(topicIds) {
  return TOPICS
    .filter((t) => topicIds.includes(t.id))
    .flatMap((t) => t.subtopics.map((s) => ({ ...s, topicId: t.id, topicName: t.name, topicEmoji: t.emoji })))
}
